### ISSUE TITLE
Should trans-corpora be processed by ourselves?

### ISSUE THREAD

**Issue by liyu-kun** [thunlp/XQA#6]
We noticed corpora lead by TRANS_DATA_DIR in config.py not exist in the XQA dataset. Are these corpora not opened and should be processed on our own?

**Comment by alphaf52** [comment]
TRANS_DATA_DIR is related to (machine) translation-based method in our paper. Experiment results show that in most settings, multi-lingual BERT performs much better than translation-based methods. I am sorry that we do not provide machine translated results in this corpora due to several reasons.

If you are going to use machine translated results. You could tell me some detail information (e.g. which part are you going to use) and I will see what I can do to help.

**Comment by liyu-kun** [comment]
Oh, we had some misunderstandings on the corpora. The corpora we want can be produced by putting corpora of multiple languages together.

Thank you for the reply.
